# Generated by Django 3.1.4 on 2020-12-31 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('idUser', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idAdmin', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAdmin', models.CharField(max_length=8)),
                ('idUser', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=8)),
                ('idUserTarget', models.CharField(max_length=8)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=8)),
                ('idUserTarget', models.CharField(max_length=8)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LikeCmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=8)),
                ('idCommentTarget', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='LikeRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=8)),
                ('idRecipes', models.CharField(max_length=8)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LikeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=8)),
                ('idUserTarget', models.CharField(max_length=8)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUserSender', models.CharField(max_length=8)),
                ('idUserReceiver', models.CharField(max_length=8)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('idRecipes', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='RecipesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRecipes', models.CharField(max_length=8)),
                ('idUser', models.CharField(max_length=8)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('idRecipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='CommentRecipe',
            fields=[
                ('idComment', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('idCommentTarget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.commentrecipe')),
                ('idRecipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.recipes')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user')),
            ],
        ),
    ]
