# Generated by Django 3.1.4 on 2020-12-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='content',
        ),
        migrations.AddField(
            model_name='recipes',
            name='contentPath',
            field=models.CharField(default='hellodir', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='dateUpload',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
