# Generated by Django 3.1.4 on 2020-12-31 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookpad', '0004_auto_20201231_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrecipe',
            name='idCommentTarget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.commentrecipe'),
        ),
    ]
