# Generated by Django 3.1.4 on 2020-12-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookpad', '0006_auto_20201231_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='idUserTarget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user'),
        ),
        migrations.AlterField(
            model_name='likecmt',
            name='idCommentTarget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.likecmt'),
        ),
        migrations.AlterField(
            model_name='likecmt',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user'),
        ),
        migrations.AlterField(
            model_name='likerecipes',
            name='idRecipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.recipes'),
        ),
        migrations.AlterField(
            model_name='likerecipes',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user'),
        ),
    ]
