# Generated by Django 3.1.4 on 2020-12-31 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookpad', '0007_auto_20201231_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecmt',
            name='idCommentTarget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.commentrecipe'),
        ),
    ]
