# Generated by Django 3.1.4 on 2020-12-31 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookpad', '0008_auto_20201231_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeuser',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user'),
        ),
        migrations.AlterField(
            model_name='likeuser',
            name='idUserTarget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user'),
        ),
    ]
