# Generated by Django 3.1.4 on 2020-12-31 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookpad', '0009_auto_20201231_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='idUserReceiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='idUserSender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user'),
        ),
    ]
