# Generated by Django 3.1.4 on 2020-12-31 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpad', '0010_auto_20201231_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 18, 44, 59, 877943)),
            preserve_default=False,
        ),
    ]
