# Generated by Django 3.1.4 on 2020-12-31 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookpad', '0011_message_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='idRecipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.recipes'),
        ),
        migrations.AlterField(
            model_name='share',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookpad.user'),
        ),
    ]
